export const COLORS = {
  player: '#00f5ff',
  invader1: '#ff00ff',
  invader2: '#39ff14',
  invader3: '#ff6600',
  bullet: '#00f5ff',
  glow: 'rgba(0, 245, 255, 0.6)',
  shield: '#00f5ff',
  double: '#39ff14',
  rocket: '#ff6600',
  heal: '#ff3366',
  pierce: '#bc13fe',
  points: '#ffff00',
  boss: '#ff0844',
  bg: '#0d0d14',
  text: '#00f5ff',
  textYellow: '#ffff00',
  textRed: '#ff0844'
};

export const CONSTANTS = {
  // --- CORE ENGINE ---
  VERSION: 'beta 0.9',
  TITLE: 'NEON INVADERS',
  BG_COLOR: 0x0d0d14,
  FPS_TARGET: 60,
  
  GAME_STATES: {
    START: 'START',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
    GAMEOVER: 'GAMEOVER',
    BOSSKILLED: 'BOSSKILLED',
    HIGHSCORE: 'HIGHSCORE',
    QUIT_CONFIRM: 'QUIT_CONFIRM'
  },

  // --- DIMENSIONS & SCALING ---
  LOGICAL_WIDTH: 800,
  LOGICAL_HEIGHT_MIN: 600,
  LOGICAL_HEIGHT_MAX: 1400,
  ASPECT_RATIO_BASE: 4 / 3,

  // --- PLAYER ---
  PLAYER_W: 40, 
  PLAYER_H: 24, 
  PLAYER_SPEED: 6,
  PLAYER_INITIAL_LIVES: 3,
  PLAYER_INITIAL_MAX_LIVES: 5,
  PLAYER_INITIAL_MAX_DAMAGE: 5,
  PLAYER_MAX_SHOT_COUNT: 4,
  PLAYER_SHOOT_COOLDOWN: 200,
  PLAYER_Y_OFFSET: 80, // Distance from bottom
  PLAYER_WINDOW_COLOR: 0x0a0a0f,
  
  // --- INVADERS ---
  INVADER_W: 36, 
  INVADER_H: 24,
  INVADER_GAP: 8,
  INVADER_TINT_MIN: 0.45,
  INVADER_TINT_RANGE: 0.55,
  INVADER_ROWS_BASE_PORTRAIT: 9,
  INVADER_ROWS_BASE_LANDSCAPE: 5,
  INVADER_COLS_BASE_PORTRAIT: 6,
  INVADER_COLS_BASE_LANDSCAPE: 11,
  INVADER_MAX_ROWS: 7, 
  INVADER_MAX_COLS: 14,
  INVADER_SHOOT_INTERVAL_BASE: 1000,
  INVADER_SHOOT_INTERVAL_MIN: 350,
  INVADER_DROP_DOWN: 20,
  INVADER_SPEED_BASE: 40,
  INVADER_SPEED_INC: 5,
  INVADER_MARGIN: 40,
  INVADER_START_Y: 140,
  
  // --- BOSSES ---
  BOSS_HP_MULT: 250, 
  BOSS_HP_MULT_MINI: 125,
  BOSS_W_MULT: 6, 
  BOSS_H_MULT: 6,
  BOSS_W_MULT_MINI: 4, 
  BOSS_H_MULT_MINI: 4,
  BOSS_SHOOT_INTERVAL: 3000,
  BOSS_SCORE: 500, 
  BOSS_SCORE_MINI: 250,
  
  // --- WEAPONS & PROJECTILES ---
  BULLET_W: 4, 
  BULLET_H: 12, 
  BULLET_SPEED: -10,
  INVADER_BULLET_W: 6, 
  INVADER_BULLET_H: 10, 
  INVADER_BULLET_SPEED: 4,
  BOSS_MISSILE_W: 8, 
  BOSS_MISSILE_H: 16, 
  BOSS_MISSILE_SPEED: 5,
  PROJECTILE_BOUNDS_BUFFER: 50,
  
  // --- ROCKETS ---
  ROCKET_W: 10, 
  ROCKET_H: 24, 
  ROCKET_INITIAL_SPEED: 1, 
  ROCKET_MAX_SPEED: 9,
  ROCKET_THRUST: 0.25, 
  ROCKET_STEER_STRENGTH: 0.12, 
  ROCKET_VERTICAL_PHASE: 55, 
  ROCKET_HIT_RADIUS: 28,
  ROCKET_INTERVAL_MS: 5000, 
  PLAYER_MAX_ROCKET_LEVEL: 5,
  
  // --- SIDEPODS (PDC & LIGHTNING) ---
  POD_W: 20, 
  POD_H: 12, 
  POD_GAP: 10, 
  POD_MAX_HP: 3,
  PDC_INTERVAL_MS: 80,
  PDC_CHANCE: 0.1,
  PDC_RANGE: 400,
  PDC_TRACER_LIFE: 40,
  LIGHTNING_INTERVAL_MS: 1000,
  LIGHTNING_DURATION_MS: 150,
  LIGHTNING_OFFSET: 30,
  LIGHTNING_SEGMENT_DIST: 30,
  
  // --- UPGRADES ---
  UPGRADE_TYPES: ['shield', 'double', 'rocket', 'pierce', 'heal', 'points'],
  DROP_CHANCE: 0.18, 
  UPGRADE_SPEED: 3,
  UPGRADE_W: 24, 
  UPGRADE_H: 24,
  UPGRADE_BOUNDS_BUFFER: 50,
  
  // --- EFFECTS & PARTICLES ---
  MAX_PARTICLES: 1024,
  EXPLOSION_PARTICLES: 18, 
  PARTICLE_MAX_SIZE: 14, 
  PARTICLE_LIFE: 28, 
  PARTICLE_SPEED: 5,
  ROCKET_TRAIL_SIZE: 5, 
  ROCKET_TRAIL_LIFE: 14, 
  ROCKET_TRAIL_DRAG: 0.25,
  SCORE_TEXT_SPEED: -3.5, 
  SCORE_TEXT_LIFE: 45,
  DAMAGE_TEXT_LIFE: 40,
  SHAKE_DECAY: 0.9,
  SHAKE_THRESHOLD: 0.1,
  SHAKE_MULTIPLIER: 2,
  SHAKE_BOSS_HIT: 1,
  SHAKE_MAX_BOSS_ACCUMULATION: 5,
  SHAKE_PLAYER_HIT: 15,
  SHAKE_POD_HIT: 10,
  SHAKE_BOSS_DEATH: 30,
  SHAKE_BIG_EXPLOSION: 40,

  // --- SPRITE BAKING ---
  SPRITE_PADDING: 40,
  SPRITE_TRANSLATE: 20,
  GLOW_BLUR: 15,

  // --- UI LAYOUT & STYLE ---
  UI_PADDING: 15,
  UI_HUD_Y: 15,
  UI_HUD_Y2_OFFSET: 25,
  UI_HEADER_Y: 100,
  UI_HIGHSCORE_Y: 220,
  UI_PROMPT_Y_OFFSET: 60,
  UI_WATERMARK_X: 20,
  UI_WATERMARK_Y_OFFSET: 45,
  UI_BORDER_THICKNESS: 2,
  UI_DEBUG_Y: 160,
  UI_MENU_ALPHA: 0.3,
  UI_CONTROLS_TEXT: '← → move · SPACE shoot · H help · ESC end',
  UI_NAME_ENTRY_HEADER_Y: 120,
  UI_NAME_ENTRY_SLOTS_Y: 240,
  UI_NAME_ENTRY_FOOTER_Y: 340,
  UI_NAME_ENTRY_GAP: 80,
  
  // Font Sizes
  FONT_SIZE_TITLE: 48,
  FONT_SIZE_SUBTITLE: 14,
  FONT_SIZE_HEADER: 24,
  FONT_SIZE_NAME_ENTRY_HEADER: 36,
  FONT_SIZE_NAME_ENTRY_CHAR: 64,
  FONT_SIZE_HUD: 16,
  FONT_SIZE_UPGRADE_LABEL: 14,
  FONT_SIZE_UPGRADE_DESC: 12,
  FONT_SIZE_PROMPT: 20,
  FONT_SIZE_VERSION_SMALL: 10,
  FONT_SIZE_SCORE_ITEM: 20,
  
  // Animations
  ANIM_BREATH_SPEED: 500,
  ANIM_BREATH_STRENGTH: 0.03,
  ANIM_BLINK_SPEED: 300,
  
  // --- Z-INDEX LAYERING ---
  Z_BG: 0,
  Z_WORLD: 10,
  Z_ENTITIES: 20,
  Z_PROJECTILES: 30,
  Z_EFFECTS: 40,
  Z_UI: 100,
  
  // --- STARFIELD ---
  STAR_LAYERS: [
    { size: 1, speed: 2.5, count: 50 }, 
    { size: 2, speed: 1.2, count: 30 },
    { size: 3, speed: 0.5, count: 15 }
  ],
  STAR_ALPHA_BASE: 0.2,
  STAR_ALPHA_INC: 0.3,

  // --- GAME LOGIC ---
  SHIELD_RECHARGE_MS: 5000,
  STAT_POTENTIAL_GAIN: 2,
  POINTS_MULTIPLIER: 100,
  BOSS_UNLOCK_LEFT: 5,
  BOSS_UNLOCK_RIGHT: 10,

  // --- TOUCH SYSTEM ---
  TOUCH_DOUBLE_TAP_MS: 300,
  TOUCH_LABEL_ALPHA: 0.15
};
