export const COLORS = {
  player: '#00f5ff',
  invader1: '#ff00ff',
  invader2: '#39ff14',
  invader3: '#ff6600',
  bullet: '#00f5ff',
  glow: 'rgba(0, 245, 255, 0.6)',
  shield: '#00f5ff',
  double: '#39ff14',
  rocket: '#ff6600',
  heal: '#ff3366',
  pierce: '#bc13fe', // New neon purple for Pierce
  points: '#ffff00', // Neon yellow for points upgrade
};

export const CONSTANTS = {
  ROCKET_W: 10, ROCKET_H: 24, ROCKET_INITIAL_SPEED: 1, ROCKET_MAX_SPEED: 9,
  ROCKET_THRUST: 0.25, ROCKET_STEER_STRENGTH: 0.12, ROCKET_VERTICAL_PHASE: 55, ROCKET_HIT_RADIUS: 28,
  UPGRADE_TYPES: ['shield', 'double', 'rocket', 'pierce', 'heal', 'points'], DROP_CHANCE: 0.18, UPGRADE_FALL_SPEED: 3,
  UPGRADE_W: 24, UPGRADE_H: 24, ROCKET_INTERVAL_MS: 5000, SHIELD_RECHARGE_MS: 5000,
  EXPLOSION_PARTICLES: 18, PARTICLE_MAX_SIZE: 14, PARTICLE_LIFE: 28, PARTICLE_SPEED: 5,
  ROCKET_TRAIL_SIZE: 5, ROCKET_TRAIL_LIFE: 14, ROCKET_TRAIL_DRAG: 0.25,
  BULLET_SPEED: -10, INVADER_BULLET_SPEED: 4, INVADER_ROWS: 5, INVADER_COLS: 11,
  INVADER_W: 36, INVADER_H: 24, INVADER_SHOOT_INTERVAL_BASE: 1000, PLAYER_SHOOT_COOLDOWN: 200,
  
  // Player Stats & Limits
  PLAYER_MAX_SHOT_COUNT: 4,
  PLAYER_MAX_ROCKET_LEVEL: 5,
  PLAYER_INITIAL_MAX_LIVES: 5,
  PLAYER_INITIAL_MAX_DAMAGE: 5,
  STAT_POTENTIAL_GAIN: 2,
  POINTS_MULTIPLIER: 100,

  // Boss Reward Levels
  BOSS_UNLOCK_LEFT: 5,
  BOSS_UNLOCK_RIGHT: 10,
  POD_MAX_HP: 3,

  // Bullets & Missiles
  BULLET_W: 4, BULLET_H: 12,
  INVADER_BULLET_W: 6, INVADER_BULLET_H: 10,
  BOSS_MISSILE_W: 8, BOSS_MISSILE_H: 16,

  // Shake Intensities
  SHAKE_BOSS_HIT: 1,
  SHAKE_MAX_BOSS_ACCUMULATION: 5,
  SHAKE_PLAYER_HIT: 15,
  SHAKE_POD_HIT: 10,
  SHAKE_BOSS_DEATH: 30,
  SHAKE_BIG_EXPLOSION: 40,

  // Lightning Attack
  LIGHTNING_INTERVAL_MS: 1000,
  LIGHTNING_DURATION_MS: 150,
  LIGHTNING_ZIGZAG_SEGMENTS: 16,
  LIGHTNING_OFFSET: 30,
  LIGHTNING_COLOR_START: '#555555',
  LIGHTNING_COLOR_END: '#00f5ff',
  LIGHTNING_GLOW: '#00f5ff',
  
  // PDC (Point Defense Cannon)
  PDC_INTERVAL_MS: 80,
  PDC_CHANCE: 0.1,
  PDC_RANGE: 400
};
